<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/images/SN_web_lightmode.png" width="300" alt="cognitiveclass.ai logo">
</center>

<h1 align=center><font size = 5>Assignment: Notebook for Graded Assessment</font></h1>

# Introduction

Using this Python notebook you will:

1.  Understand three Chicago datasets
2.  Load the three datasets into three tables in a SQLIte database
3.  Execute SQL queries to answer assignment questions

## Understand the datasets

To complete the assignment problems in this notebook you will be using three datasets that are available on the city of Chicago's Data Portal:

1.  <a href="https://data.cityofchicago.org/Health-Human-Services/Census-Data-Selected-socioeconomic-indicators-in-C/kn9c-c2s2?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01">Socioeconomic Indicators in Chicago</a>
2.  <a href="https://data.cityofchicago.org/Education/Chicago-Public-Schools-Progress-Report-Cards-2011-/9xs2-f89t?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01">Chicago Public Schools</a>
3.  <a href="https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-present/ijzp-q8t2?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01">Chicago Crime Data</a>

### 1. Socioeconomic Indicators in Chicago

This dataset contains a selection of six socioeconomic indicators of public health significance and a “hardship index,” for each Chicago community area, for the years 2008 – 2012.

A detailed description of this dataset and the original dataset can be obtained from the Chicago Data Portal at:

[https://data.cityofchicago.org/Health-Human-Services/Census-Data-Selected-socioeconomic-indicators-in-C/kn9c-c2s2](https://data.cityofchicago.org/Health-Human-Services/Census-Data-Selected-socioeconomic-indicators-in-C/kn9c-c2s2?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01&cm_mmc=Email_Newsletter-\_-Developer_Ed%2BTech-\_-WW_WW-\_-SkillsNetwork-Courses-IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork-20127838&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ)

### 2. Chicago Public Schools

This dataset shows all school level performance data used to create CPS School Report Cards for the 2011-2012 school year. This dataset is provided by the city of Chicago's Data Portal.

A detailed description of this dataset and the original dataset can be obtained from the Chicago Data Portal at:

[https://data.cityofchicago.org/Education/Chicago-Public-Schools-Progress-Report-Cards-2011-/9xs2-f89t](https://data.cityofchicago.org/Education/Chicago-Public-Schools-Progress-Report-Cards-2011-/9xs2-f89t?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01&cm_mmc=Email_Newsletter-\_-Developer_Ed%2BTech-\_-WW_WW-\_-SkillsNetwork-Courses-IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork-20127838&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ)

### 3. Chicago Crime Data

This dataset reflects reported incidents of crime (with the exception of murders where data exists for each victim) that occurred in the City of Chicago from 2001 to present, minus the most recent seven days.

A detailed description of this dataset and the original dataset can be obtained from the Chicago Data Portal at:

[https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-present/ijzp-q8t2](https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-present/ijzp-q8t2?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01&cm_mmc=Email_Newsletter-\_-Developer_Ed%2BTech-\_-WW_WW-\_-SkillsNetwork-Courses-IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork-20127838&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ)

### Download the datasets

This assignment requires you to have these three tables populated with a subset of the whole datasets.

In many cases the dataset to be analyzed is available as a .CSV (comma separated values) file, perhaps on the internet. 

Use the links below to read the data files using the Pandas library. 

* Chicago Census Data

https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoCensusData.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01

* Chicago Public Schools

https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoPublicSchools.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01

* Chicago Crime Data

https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoCrimeData.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01

**NOTE:** Ensure you use the datasets available on the links above instead of directly from the Chicago Data Portal. The versions linked here are subsets of the original datasets and have some of the column names modified to be more database friendly which will make it easier to complete this assignment.

### Store the datasets in database tables

To analyze the data using SQL, it first needs to be loaded into SQLite DB.
We will create three tables in as under:

1.  **CENSUS_DATA**
2.  **CHICAGO_PUBLIC_SCHOOLS**
3.  **CHICAGO_CRIME_DATA**

Load the `pandas` and `sqlite3` libraries and establish a connection to `FinalDB.db`

In [1]:
import csv, sqlite3

con = sqlite3.connect("FinalDB.db")
cur = con.cursor()

Load the SQL magic module

In [5]:
import pandas
df = pandas.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoCensusData.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01")
df.to_sql("CENSUS_DATA", con, if_exists='replace', index=False,method="multi")

df = pandas.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoCrimeData.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01")
df.to_sql("CHICAGO_CRIME_DATA", con, if_exists='replace', index=False, method="multi")

df = pandas.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoPublicSchools.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01")
df.to_sql("CHICAGO_PUBLIC_SCHOOLS_DATA", con, if_exists='replace', index=False, method="multi")

/home/jupyterlab/conda/envs/python/lib/python3.7/site-packages/pandas/core/generic.py:2615: UserWarning: The spaces in these column names will not be changed. In pandas versions < 0.14, spaces were converted to underscores.
  method=method,

Use `Pandas` to load the data available in the links above to dataframes. Use these dataframes to load data on to the database `FinalDB.db` as required tables.

In [6]:
%load_ext sql

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

Establish a connection between SQL magic module and the database `FinalDB.db`

In [7]:
%sql sqlite:///FinalDB.db

'Connected: @FinalDB.db'

You can now proceed to the the following questions. Please note that a graded assignment will follow this lab and there will be a question on each of the problems stated below. It can be from the answer you received or the code you write for this problem. Therefore, please keep a note of both your codes as well as the response you generate.

## Problems

Now write and execute SQL queries to solve assignment problems

### Problem 1

##### Find the total number of crimes recorded in the CRIME table.

In [8]:
%sql select count(*) from CHICAGO_CRIME_DATA

 * sqlite:///FinalDB.db
Done.

[(533,)]

### Problem 2

##### List community area names and numbers with per capita income less than 11000.

In [12]:
%sql SELECT "community_area_name", "ca"  \
     from CENSUS_DATA \
     where "per_capita_income_" < 11000 \
        order by "ca"

 * sqlite:///FinalDB.db
Done.

[]

### Problem 3

##### List all case numbers for crimes involving minors?(children are not considered minors for the purposes of crime analysis)

In [25]:
%sql SELECT "community_area", "id" \
     from CHICAGO_CRIME_DATA \
         where "location" = "school"

 * sqlite:///FinalDB.db
Done.

[]

### Problem 4

##### List all kidnapping crimes involving a child?

In [26]:
%sql SELECT "community_area", "id" \
     from CHICAGO_CRIME_DATA \
         where "location" = "school"

 * sqlite:///FinalDB.db
Done.

[]

### Problem 5

##### List the kind of crimes that were recorded at schools. (No repetitions)

In [24]:
%sql SELECT *  \
     from CHICAGO_CRIME_DATA \
         where "location" = "school"

 * sqlite:///FinalDB.db
Done.

[]

### Problem 6

##### List the type of schools along with the average safety score for each type.

In [ ]:
%sql SELECT *  \
     from CHICAGO_CRIME_DATA \
         where "location" = "school"

### Problem 7

##### List 5 community areas with highest % of households below poverty line

In [15]:
%sql select "community_area_name", "ca" \
   from CENSUS_DATA \
   where "percent_households_below_poverty" \
        order by "community_area_name" \
   LIMIT 5

 * sqlite:///FinalDB.db
Done.

[('Albany Park', 'ca'),
 ('Archer Heights', 'ca'),
 ('Armour Square', 'ca'),
 ('Ashburn', 'ca'),
 ('Auburn Gresham', 'ca')]

### Problem 8

##### Which community area is most crime prone? Display the coumminty area number only.

In [21]:
%sql SELECT "community_area", "id"  \
     from CHICAGO_CRIME_DATA \
        order by "id" DESC

 * sqlite:///FinalDB.db
Done.

[('community_area', 11277173),
 ('community_area', 11233321),
 ('community_area', 11230490),
 ('community_area', 11185730),
 ('community_area', 11185089),
 ('community_area', 11184062),
 ('community_area', 11178752),
 ('community_area', 11143628),
 ('community_area', 11137994),
 ('community_area', 11133668),
 ('community_area', 11127628),
 ('community_area', 11122168),
 ('community_area', 11111810),
 ('community_area', 11110571),
 ('community_area', 11106461),
 ('community_area', 11072808),
 ('community_area', 11057640),
 ('community_area', 11056591),
 ('community_area', 11048967),
 ('community_area', 11018984),
 ('community_area', 11014534),
 ('community_area', 10952376),
 ('community_area', 10950230),
 ('community_area', 10943516),
 ('community_area', 10931066),
 ('community_area', 10904332),
 ('community_area', 10882712),
 ('community_area', 10879266),
 ('community_area', 10840565),
 ('community_area', 10831592),
 ('community_area', 10811959),
 ('community_area', 10808622),
 ('community_area', 10787573),
 ('community_area', 10779118),
 ('community_area', 10770065),
 ('community_area', 10769475),
 ('community_area', 10760731),
 ('community_area', 10707046),
 ('community_area', 10679671),
 ('community_area', 10653179),
 ('community_area', 10626372),
 ('community_area', 10625887),
 ('community_area', 10624311),
 ('community_area', 10619033),
 ('community_area', 10585295),
 ('community_area', 10584429),
 ('community_area', 10574810),
 ('community_area', 10562980),
 ('community_area', 10549382),
 ('community_area', 10502099),
 ('community_area', 10501619),
 ('community_area', 10493762),
 ('community_area', 10488465),
 ('community_area', 10485657),
 ('community_area', 10453948),
 ('community_area', 10409937),
 ('community_area', 10402076),
 ('community_area', 10399689),
 ('community_area', 10397129),
 ('community_area', 10327846),
 ('community_area', 10270593),
 ('community_area', 10268721),
 ('community_area', 10268156),
 ('community_area', 10225755),
 ('community_area', 10218934),
 ('community_area', 10209850),
 ('community_area', 10197369),
 ('community_area', 10190267),
 ('community_area', 10179921),
 ('community_area', 10177662),
 ('community_area', 10102551),
 ('community_area', 10084732),
 ('community_area', 10079280),
 ('community_area', 10070513),
 ('community_area', 10046030),
 ('community_area', 10025545),
 ('community_area', 10015483),
 ('community_area', 10012707),
 ('community_area', 10003235),
 ('community_area', 9999493),
 ('community_area', 9993135),
 ('community_area', 9978032),
 ('community_area', 9974424),
 ('community_area', 9902691),
 ('community_area', 9859793),
 ('community_area', 9817983),
 ('community_area', 9806771),
 ('community_area', 9801245),
 ('community_area', 9748574),
 ('community_area', 9704121),
 ('community_area', 9692995),
 ('community_area', 9682442),
 ('community_area', 9681782),
 ('community_area', 9664739),
 ('community_area', 9651438),
 ('community_area', 9612532),
 ('community_area', 9608166),
 ('community_area', 9589300),
 ('community_area', 9575333),
 ('community_area', 9556192),
 ('community_area', 9551405),
 ('community_area', 9509922),
 ('community_area', 9499852),
 ('community_area', 9499538),
 ('community_area', 9491052),
 ('community_area', 9458866),
 ('community_area', 9434484),
 ('community_area', 9432406),
 ('community_area', 9426342),
 ('community_area', 9425197),
 ('community_area', 9419053),
 ('community_area', 9416016),
 ('community_area', 9413737),
 ('community_area', 9383468),
 ('community_area', 9348957),
 ('community_area', 9337353),
 ('community_area', 9305467),
 ('community_area', 9296677),
 ('community_area', 9271865),
 ('community_area', 9269662),
 ('community_area', 9204493),
 ('community_area', 9166453),
 ('community_area', 9129599),
 ('community_area', 9116765),
 ('community_area', 9094512),
 ('community_area', 9088959),
 ('community_area', 9068374),
 ('community_area', 9035595),
 ('community_area', 9012649),
 ('community_area', 8921455),
 ('community_area', 8921352),
 ('community_area', 8901424),
 ('community_area', 8899397),
 ('community_area', 8875058),
 ('community_area', 8863261),
 ('community_area', 8861185),
 ('community_area', 8854340),
 ('community_area', 8841511),
 ('community_area', 8805149),
 ('community_area', 8789058),
 ('community_area', 8789017),
 ('community_area', 8784049),
 ('community_area', 8771351),
 ('community_area', 8727329),
 ('community_area', 8718715),
 ('community_area', 8693981),
 ('community_area', 8690635),
 ('community_area', 8681629),
 ('community_area', 8681171),
 ('community_area', 8678872),
 ('community_area', 8670090),
 ('community_area', 8652732),
 ('community_area', 8594911),
 ('community_area', 8594622),
 ('community_area', 8592856),
 ('community_area', 8568365),
 ('community_area', 8557804),
 ('community_area', 8536808),
 ('community_area', 8533129),
 ('community_area', 8508682),
 ('community_area', 8418606),
 ('community_area', 8388644),
 ('community_area', 8321464),
 ('community_area', 8315579),
 ('community_area', 8306557),
 ('community_area', 8300838),
 ('community_area', 8223830),
 ('community_area', 8210615),
 ('community_area', 8200440),
 ('community_area', 8193625),
 ('community_area', 8169210),
 ('community_area', 8159639),
 ('community_area', 8155450),
 ('community_area', 8142216),
 ('community_area', 8134254),
 ('community_area', 8119054),
 ('community_area', 8089415),
 ('community_area', 8082600),
 ('community_area', 8020403),
 ('community_area', 8006283),
 ('community_area', 8002131),
 ('community_area', 7991098),
 ('community_area', 7947964),
 ('community_area', 7937542),
 ('community_area', 7903289),
 ('community_area', 7881407),
 ('community_area', 7868443),
 ('community_area', 7865597),
 ('community_area', 7787295),
 ('community_area', 7781193),
 ('community_area', 7762423),
 ('community_area', 7759940),
 ('community_area', 7732712),
 ('community_area', 7724785),
 ('community_area', 7692354),
 ('community_area', 7692081),
 ('community_area', 7670858),
 ('community_area', 7646435),
 ('community_area', 7623578),
 ('community_area', 7578055),
 ('community_area', 7511512),
 ('community_area', 7505841),
 ('community_area', 7502426),
 ('community_area', 7468176),
 ('community_area', 7428379),
 ('community_area', 7427845),
 ('community_area', 7410895),
 ('community_area', 7399281),
 ('community_area', 7363357),
 ('community_area', 7357439),
 ('community_area', 7287599),
 ('community_area', 7281380),
 ('community_area', 7260480),
 ('community_area', 7255767),
 ('community_area', 7195847),
 ('community_area', 7185163),
 ('community_area', 7174283),
 ('community_area', 7173960),
 ('community_area', 7172285),
 ('community_area', 7166946),
 ('community_area', 7136001),
 ('community_area', 7125811),
 ('community_area', 7097303),
 ('community_area', 7083209),
 ('community_area', 7054414),
 ('community_area', 7041136),
 ('community_area', 7002482),
 ('community_area', 6993831),
 ('community_area', 6987751),
 ('community_area', 6986273),
 ('community_area', 6982403),
 ('community_area', 6980726),
 ('community_area', 6940315),
 ('community_area', 6939024),
 ('community_area', 6937224),
 ('community_area', 6906555),
 ('community_area', 6903733),
 ('community_area', 6901330),
 ('community_area', 6900303),
 ('community_area', 6884465),
 ('community_area', 6866556),
 ('community_area', 6855661),
 ('community_area', 6806337),
 ('community_area', 6793833),
 ('community_area', 6780581),
 ('community_area', 6780235),
 ('community_area', 6777303),
 ('community_area', 6769056),
 ('community_area', 6731976),
 ('community_area', 6723496),
 ('community_area', 6720028),
 ('community_area', 6713046),
 ('community_area', 6673746),
 ('community_area', 6672913),
 ('community_area', 6644648),
 ('community_area', 6644618),
 ('community_area', 6622100),
 ('community_area', 6620347),
 ('community_area', 6588112),
 ('community_area', 6514506),
 ('community_area', 6481371),
 ('community_area', 6441121),
 ('community_area', 6270946),
 ('community_area', 6252456),
 ('community_area', 6239811),
 ('community_area', 6233210),
 ('community_area', 6231712),
 ('community_area', 6186267),
 ('community_area', 6183080),
 ('community_area', 6170783),
 ('community_area', 6155786),
 ('community_area', 6054992),
 ('community_area', 6016285),
 ('community_area', 6007606),
 ('community_area', 5989011),
 ('community_area', 5979106),
 ('community_area', 5931425),
 ('community_area', 5925338),
 ('community_area', 5904817),
 ('community_area', 5844831),
 ('community_area', 5835389),
 ('community_area', 5827212),
 ('community_area', 5784844),
 ('community_area', 5766654),
 ('community_area', 5758092),
 ('community_area', 5753121),
 ('community_area', 5744223),
 ('community_area', 5738893),
 ('community_area', 5733472),
 ('community_area', 5715871),
 ('community_area', 5713696),
 ('community_area', 5677874),
 ('community_area', 5663639),
 ('community_area', 5638846),
 ('community_area', 5635192),
 ('community_area', 5625404),
 ('community_area', 5613705),
 ('community_area', 5601454),
 ('community_area', 5567780),
 ('community_area', 5561014),
 ('community_area', 5547866),
 ('community_area', 5450649),
 ('community_area', 5448716),
 ('community_area', 5401018),
 ('community_area', 5378309),
 ('community_area', 5372669),
 ('community_area', 5360488),
 ('community_area', 5343947),
 ('community_area', 5322667),
 ('community_area', 5276766),
 ('community_area', 5260944),
 ('community_area', 5228794),
 ('community_area', 5226574),
 ('community_area', 5214424),
 ('community_area', 5176248),
 ('community_area', 5161792),
 ('community_area', 5136468),
 ('community_area', 5080475),
 ('community_area', 5053244),
 ('community_area', 4965099),
 ('community_area', 4946261),
 ('community_area', 4929211),
 ('community_area', 4921404),
 ('community_area', 4920006),
 ('community_area', 4892475),
 ('community_area', 4826872),
 ('community_area', 4810471),
 ('community_area', 4778195),
 ('community_area', 4766490),
 ('community_area', 4750131),
 ('community_area', 4746425),
 ('community_area', 4728934),
 ('community_area', 4718689),
 ('community_area', 4700014),
 ('community_area', 4681320),
 ('community_area', 4646705),
 ('community_area', 4620332),
 ('community_area', 4607081),
 ('community_area', 4606754),
 ('community_area', 4533063),
 ('community_area', 4494340),
 ('community_area', 4483436),
 ('community_area', 4448011),
 ('community_area', 4430638),
 ('community_area', 4424181),
 ('community_area', 4389244),
 ('community_area', 4385612),
 ('community_area', 4374455),
 ('community_area', 4349267),
 ('community_area', 4328714),
 ('community_area', 4317595),
 ('community_area', 4303010),
 ('community_area', 4273693),
 ('community_area', 4249096),
 ('community_area', 4223368),
 ('community_area', 4153041),
 ('community_area', 4136958),
 ('community_area', 4110831),
 ('community_area', 4084479),
 ('community_area', 4074763),
 ('community_area', 4072241),
 ('community_area', 4067549),
 ('community_area', 4044725),
 ('community_area', 4044375),
 ('community_area', 4031070),
 ('community_area', 4029579),
 ('community_area', 4006321),
 ('community_area', 3987219),
 ('community_area', 3970108),
 ('community_area', 3969617),
 ('community_area', 3943561),
 ('community_area', 3929767),
 ('community_area', 3906764),
 ('community_area', 3880644),
 ('community_area', 3867425),
 ('community_area', 3864164),
 ('community_area', 3842013),
 ('community_area', 3830058),
 ('community_area', 3823238),
 ('community_area', 3812293),
 ('community_area', 3808095),
 ('community_area', 3778925),
 ('community_area', 3761051),
 ('community_area', 3741570),
 ('community_area', 3710918),
 ('community_area', 3704662),
 ('community_area', 3680034),
 ('community_area', 3672175),
 ('community_area', 3663835),
 ('community_area', 3661130),
 ('community_area', 3646946),
 ('community_area', 3637126),
 ('community_area', 3607386),
 ('community_area', 3588432),
 ('community_area', 3530721),
 ('community_area', 3512276),
 ('community_area', 3500168),
 ('community_area', 3434215),
 ('community_area', 3426362),
 ('community_area', 3420516),
 ('community_area', 3406613),
 ('community_area', 3398799),
 ('community_area', 3395645),
 ('community_area', 3349359),
 ('community_area', 3324217),
 ('community_area', 3314082),
 ('community_area', 3313069),
 ('community_area', 3310641),
 ('community_area', 3305754),
 ('community_area', 3300223),
 ('community_area', 3280399),
 ('community_area', 3269495),
 ('community_area', 3266814),
 ('community_area', 3248961),
 ('community_area', 3225932),
 ('community_area', 3225630),
 ('community_area', 3121541),
 ('community_area', 3116759),
 ('community_area', 3114653),
 ('community_area', 3108542),
 ('community_area', 3085845),
 ('community_area', 3081572),
 ('community_area', 3072896),
 ('community_area', 3064175),
 ('community_area', 3047178),
 ('community_area', 3046354),
 ('community_area', 3020236),
 ('community_area', 3017838),
 ('community_area', 3013050),
 ('community_area', 2988938),
 ('community_area', 2975480),
 ('community_area', 2973642),
 ('community_area', 2973220),
 ('community_area', 2963994),
 ('community_area', 2961173),
 ('community_area', 2953056),
 ('community_area', 2948095),
 ('community_area', 2910492),
 ('community_area', 2906269),
 ('community_area', 2903068),
 ('community_area', 2891261),
 ('community_area', 2889910),
 ('community_area', 2866020),
 ('community_area', 2862972),
 ('community_area', 2859254),
 ('community_area', 2811745),
 ('community_area', 2804858),
 ('community_area', 2774880),
 ('community_area', 2771112),
 ('community_area', 2766777),
 ('community_area', 2748713),
 ('community_area', 2723161),
 ('community_area', 2709601),
 ('community_area', 2688426),
 ('community_area', 2679112),
 ('community_area', 2666808),
 ('community_area', 2645724),
 ('community_area', 2620109),
 ('community_area', 2584554),
 ('community_area', 2522757),
 ('community_area', 2514430),
 ('community_area', 2495142),
 ('community_area', 2492280),
 ('community_area', 2423472),
 ('community_area', 2415583),
 ('community_area', 2412250),
 ('community_area', 2405698),
 ('community_area', 2403623),
 ('community_area', 2391105),
 ('community_area', 2382981),
 ('community_area', 2364511),
 ('community_area', 2355174),
 ('community_area', 2341955),
 ('community_area', 2325074),
 ('community_area', 2316019),
 ('community_area', 2290580),
 ('community_area', 2281487),
 ('community_area', 2269553),
 ('community_area', 2225484),
 ('community_area', 2219750),
 ('community_area', 2200712),
 ('community_area', 2169996),
 ('community_area', 2164207),
 ('community_area', 2159382),
 ('community_area', 2116573),
 ('community_area', 2109180),
 ('community_area', 2103277),
 ('community_area', 2100965),
 ('community_area', 2088541),
 ('community_area', 2075734),
 ('community_area', 2065876),
 ('community_area', 2048711),
 ('community_area', 2003966),
 ('community_area', 2000970),
 ('community_area', 1962624),
 ('community_area', 1959865),
 ('community_area', 1887291),
 ('community_area', 1850651),
 ('community_area', 1845995),
 ('community_area', 1826250),
 ('community_area', 1825533),
 ('community_area', 1819413),
 ('community_area', 1806896),
 ('community_area', 1803248),
 ('community_area', 1790731),
 ('community_area', 1778867),
 ('community_area', 1762743),
 ('community_area', 1729799),
 ('community_area', 1720702),
 ('community_area', 1719296),
 ('community_area', 1639049),
 ('community_area', 1612358),
 ('community_area', 1603886),
 ('community_area', 1580040),
 ('community_area', 1577428),
 ('community_area', 1570987),
 ('community_area', 1553689),
 ('community_area', 1516518),
 ('community_area', 1476982),
 ('community_area', 1465880),
 ('community_area', 1455002),
 ('community_area', 1448800),
 ('community_area', 1438213),
 ('community_area', 1427912),
 ('community_area', 1419496),
 ('community_area', 1414626),
 ('community_area', 1367327),
 ('community_area', 1363954),
 ('community_area', 1353618),
 ('community_area', 1340847),
 ('community_area', 1326195),
 ('community_area', 23469),
 ('community_area', 21149)]


Double-click **here** for a hint

<!--
Query for the 'community area number' that has most number of incidents
-->

### Problem 9

##### Use a sub-query to find the name of the community area with highest hardship index

### Problem 10

##### Use a sub-query to determine the Community Area Name with most number of crimes?

## Author(s)

<h4> Hima Vasudevan </h4>
<h4> Rav Ahuja </h4>
<h4> Ramesh Sannreddy </h4>

## Contribtuor(s)

<h4> Malika Singla </h4>
<h4>Abhishek Gagneja</h4>

## Change log

| Date       | Version | Changed by        | Change Description                             |
| ---------- | ------- | ----------------- | ---------------------------------------------- |
|2023-10-18  | 2.6     | Abhishek Gagneja  | Modified instruction set |
| 2022-03-04 | 2.5     | Lakshmi Holla     | Changed markdown.                   |
| 2021-05-19 | 2.4     | Lakshmi Holla     | Updated the question                           |
| 2021-04-30 | 2.3     | Malika Singla     | Updated the libraries                          |
| 2021-01-15 | 2.2     | Rav Ahuja         | Removed problem 11 and fixed changelog         |
| 2020-11-25 | 2.1     | Ramesh Sannareddy | Updated the problem statements, and datasets   |
| 2020-09-05 | 2.0     | Malika Singla     | Moved lab to course repo in GitLab             |
| 2018-07-18 | 1.0     | Rav Ahuja         | Several updates including loading instructions |
| 2018-05-04 | 0.1     | Hima Vasudevan    | Created initial version                        |

## <h3 align="center"> © IBM Corporation 2023. All rights reserved. <h3/>